### PR TITLE
Detail iOS 7 issue in wifidog.conf

### LINKED ISSUE #14: how to block IOS to auto open portal ?
I want to blokc the IOS to auto open the portal, but still need to login over safari or other app.
Since IPs of  FQDNs will change because of load balancing and geo location and wifidog just support use ip in it's firewall. So how to whitelist FQDNs ？ 

FQDNs like these:
www.appleiphonecell.com
captive.apple.com
www.apple.com
www.itools.info
www.ibook.info
www.airport.us
www.thinkdifferent.us

### PR DESCRIPTION
**Pull request by mhaas**
@sinkcup can you confirm this is everything that's needed for iOS7?

Fixes #14

### CODE REVIEW

**Comment by acv** [comment]
How is the DNS to IP resolution not going stale? I though the DNS would be resolved at time of rule creation.

**Comment by missionrulz** [comment]
I was wondering the same thing @acv. @sinkcup, can you confirm on this? Does dnsmasq periodically update the user defined ipsets in the background? Or do we have to force the updates.

**Comment by mhaas** [comment]
@avc I guess the underlying assumption is that the IP is static per region and never changes.
For round-robin DNS, you probably need ipset.

@missionrulz Just to clarify, this feature is different from ipset support. dnsmasq always updates the ipset if there is a query and a new IP is sent back. Of course, if you configure it to do so.

**Comment by sinkcup** [comment]
@mhaas this conf is OK.
when use iptables to add a domain, iptables auto convert it to ip.
Wifidog support root domain and auto pass subdomain, If IP of the domain changed, need re-add it, it's a bug, I will fix it, I will create a new issue about it.

**Comment by mhaas** [comment]
Perhaps we can document two solutions: one as described here and one via dnsmasq/ipset.

**Comment by florida63** [comment]
Wiki can also be used for documents.

**Comment by mhaas** [comment]
@florida63 Can we reconsider closing this PR? It's just a two-line patch that might make life a lot easier for some people out there.

**Comment by sinkcup** [comment]
It's my mistake, I forgot to add apple into the conf, @mhaas you can merge it directly, it's a small but useful change.

**Pull request merged**
