### PR TITLE
Feature disconnect command

### PR DESCRIPTION
**Pull request by florida63**
Patch directed by Wichert order to have the possibility of a disconnected user.

see http://dev.wifidog.org/ticket/465

To try

### CODE REVIEW

**Comment by acv** [comment]
Seems good.

**Comment by florida63** [comment]
Someone else can confirm ?

**Comment by acv** [comment]
Sorry I broke the merge ...

**Comment by florida63** [comment]
It's corrected.

**Comment by acv** [comment]
OK, well, let's merge this.

**Comment by acv** [comment]
This should fix issue #17

**Pull request merged**
