### PR TITLE
Optimization of Iptable chain names used by WifiDog

### PR DESCRIPTION
**Pull request by florida63**

### CODE REVIEW

**Comment by florida63** [comment]
@shogsbro : I took your work on the optimization of iptables chain and the abbreviation used by the nodogsplash project.

Can you test.

@benoigt: what do you think. I know that you had already addressed this problem via http://dev.wifidog.org/ticket/515.

**Comment by shogsbro** [comment]
Hi,

Interesting, so there is active life in this project?

I am having issues getting wifidog to capture the traffic. I reached
conclusion tonight that wifidog assumes the connection is NAT'ted, which I
will verify tomorrow. Is this correct?

Is this a NetFilter restriction? Could the REDIRECT not be inserted in
PREROUTING chain without using NAT?

In any event, I found the Developer and V2 pages and am wondering what work
is ongoing there?

I implemented a basic Auth server to test this, using Bottle and Python.

I would personally prefer that the Author server decided which traffic to
block, such that fine-grained network control would be feasible. Automatic
hand-off between WifiDog instances would be great.

Is there interest in taking V2 in that direction? Or should I just start
afresh?

Regards,

Sigurd

**Comment by benoitg** [comment]
@florida63 Well, the names are near unreadable now, I would have kept the last part longer.  But if it's absolutely necessary, ok.

**Comment by florida63** [comment]
@benoigt: In some cases, the id of the interface and superior has 8 characters which can pose problem because the iptables chain is too long. This led me to optimize.
  
I agree with you about the readability, I have little being was radical and I also wanted to keep the same logic as nodogsplash.
A good compromise could be to do something like:
define CHAIN_TO_INTERNET "WD_ $ ID $ _Internet"
instead of
define CHAIN_WIFI_TO_INTERNET "WiFiDog_ $ ID $ _WIFI2Internet."
in this case, there is more margin.

@shogsbro: For your comment and your questions benoigt has more experience than me on this project.

**Pull request closed without merging**
