### PR TITLE
Add clang and CyaSSL to the build matrix

### PR DESCRIPTION
**Pull request by mhaas**
We use the travis cache to avoid re-building CyaSSL.

On a cold cache, CyaSSL is downloaded from github into dependencies-src/
and installed into dependencies-installed/. Both directories are added to the
Travis cache.

### CODE REVIEW

**Comment by acv** [comment]
Looks great.

**Comment by acv** [comment]
I had to revert this... The problem is commit d2a9b542cd8989ac8d263bcd3bea05901669d89f

**Comment by acv** [comment]
I shouldn't github before coffee. This merge was fine because f02b6ff restored the code to what it originally did.

**Comment by mhaas** [comment]
I reverted that particular commit and put in a workaround. 

Am 22. März 2015 14:46:26 MEZ, schrieb Alexandre Carmel-Veilleux <notifications@github.com>:

**Comment by acv** [comment]
I saw... So reverted my revert... Feeling pretty dumb.

**Comment by mhaas** [comment]
Don't worry about it. I felt dumb about my false positive as well.

Am 22. März 2015 14:52:20 MEZ, schrieb Alexandre Carmel-Veilleux <notifications@github.com>:

**Pull request merged**
