### PR TITLE
Fix leak and fix indent so I could understand code

### PR DESCRIPTION
**Pull request by acv**
Another coverity detected memory leak, `url` and possibly `urlFragment` were not being freed.

### CODE REVIEW

**Comment by mhaas** [comment]
Is coverity scan up and running? I had it set up via Travis. Are you using direct github integration? 

Am 22. März 2015 15:48:31 MEZ, schrieb Alexandre Carmel-Veilleux <notifications@github.com>:

**Comment by acv** [comment]
I'm doing the scans manually.

**Comment by florida63** [comment]
@acv : can you separate your commit when it concerns indentation. it allows a better readability patches.

**Comment by acv** [comment]
Yeah, I screwed up this one. That's why I put comments at the two change spots.

**Comment by acv** [comment]
@florida63: If you really want, I could re-do the fix with separate commits. The actual change however is just two `free()` calls before a `return` in error path.

**Comment by mhaas** [comment]
I don't mind, but you started that rule of separate commits.. No, let it slide. But it's not super useful to open PRs for review in this case because there's too much noise.

**Comment by acv** [comment]
I re-did my commit with 2 separate commits for reviewing.

**Comment by florida63** [comment]
@acv: it's much better

you are a chef :)

**Pull request merged**
