### PR TITLE
Prepare release 1.3.0

### PR DESCRIPTION
**Pull request by mhaas**
It's time we did a new release to bring MUSL and wolfSSL fixes to the OpenWRT people. Since master also contains new features, this release becomes 1.3.0 rather than 1.2.2.

### CODE REVIEW

**Comment by t123yh** [comment]
When to release 1.3.0?

**Comment by KazukiShimada** [comment]
@acv 
Hi, Alex. How are you? still busy?
Thanks in advance.

**Comment by acv** [comment]
I have no issues with cutting a new 1.3.0.

**Comment by mhaas** [comment]
I have just cut release 1.3.0. Thanks to all contributors!

https://github.com/wifidog/wifidog-gateway/releases/tag/1.3.0

**Comment by KazukiShimada** [comment]
@mhaas 
Thanks!

**Pull request merged**
