### PR TITLE
Enhance safe_malloc to always zero memory

### PR DESCRIPTION
**Pull request by acv**
This is to fix issue #154

### CODE REVIEW

**Comment by mhaas** [comment]
Thanks, great patch.

**Comment by champtar** [comment]
Hi @acv
You should use calloc
Regards

**Comment by acv** [comment]
Hi @champtar 

This is the uClibc implementation of calloc:

```C
void * calloc(size_t nmemb, size_t lsize)
{
	void *result;
	size_t size=lsize * nmemb;

	/* guard vs integer overflow, but allow nmemb
	 * to fall through and call malloc(0) */
	if (nmemb && lsize != (size / nmemb)) {
		__set_errno(ENOMEM);
		return NULL;
	}
	if ((result=malloc(size)) != NULL) {
		memset(result, 0, size);
	}
	return result;
}
```

So basically, the same as our implementation where `nmemb` would be `size` and `lsize` would always be 1.

**Comment by champtar** [comment]
Yep but you might use another libc like musl in the future, or glibc, or ...

**Comment by mhaas** [comment]
Calloc and malloc + member (0) are semantically equivalent, so it does not really matter 

Am 24. März 2015 19:59:02 MEZ, schrieb champtar <notifications@github.com>:

**Pull request merged**
