### PR TITLE
Libhttpd upgrade to 1.4

### PR DESCRIPTION
**Pull request by acv**
This is a work in progress with the objective of upgrading libhttpd by picking the parts that make sense from 1.4 and cherry-picking bug fixes from nodogsplash.

Motivation is issue #87

### CODE REVIEW

**Comment by acv** [comment]
First commit imports the httpdSetVariableValue() symbol, upgrades it with request support and actually adds it to public header so it can be used. I guess it was added for Ember and Ember had some extern definitions for it.

**Comment by acv** [comment]
Before anyone complain about indentation. Last commit in this PR will be a run through with `indent`.

**Comment by acv** [comment]
httpdSendFile addition and httpdAuthenticate fix.

This most likely broke the gateway itself due to public interface change. Will fix before we get to a merge.

**Comment by acv** [comment]
Added support for `httpdSetErrorFunction` and removed `httpdAddC404Content` which we'd put in to do the same thing.

**Comment by acv** [comment]
There's a templating support built-in to libhttpd 1.4 in the form of `_httpd_sendExpandedText` do we want that support? Will we even use it?

**Comment by acv** [comment]
I am not importing support for Ember into the code. We don't need a templating engine and I'd have to overhaul all the build machinery to find it and all that.

**Comment by mhaas** [comment]
I reviewed 9402599. Looks good. Merged!

**Pull request merged**
