### PR TITLE
Open firewall when auth server are down

### PR DESCRIPTION
**Pull request by acv**
See issue #90.

This is a work in progress, right now only ticket92src.diff has been manually applied. It builds however. Next up config ticket. Then fix the highlighted issue if there's no config.

### CODE REVIEW

**Comment by acv** [comment]
Last commit adds the missing feature from issue #90, if there's not auth-is-down ruleset, then the default "Sorry" page should be shown.

Needs testing.

**Comment by acv** [comment]
Patch doesn't seem to quite work.

**Comment by acv** [comment]
Somehow the AuthIsDown rules aren't catching.

**Comment by acv** [comment]
Missing firewall rule added.

Can anyone else test this? Worked between my VMs.

**Comment by acv** [comment]
@mhaas @florida63 Can either of you sanity check this patch?

**Comment by florida63** [comment]
@acv: I'll try to take the time to test. I'll let you know.

The code looks good to me.

**Comment by mhaas** [comment]
Code looks good.

**Comment by florida63** [comment]
Please wait before merged 1.2.1

**Comment by mhaas** [comment]
@florida63 I don't understand - do you want this in for 1.2.1?

**Comment by florida63** [comment]
This new feature could possibly be added in 1.2.1 without waiting 1.3.0.

I look at that right now to be sure that it's working properly.
That's why I asked to wait if other intended to merged.

**Comment by florida63** [comment]
It works for me, although it corrects the problem with the page uh oh.

Thought has update changelog before merged.

**Comment by acv** [comment]
I find it easier to do the NEWS update as a separate pull request because updating NEWS is a prime source of merge conflicts.

**Comment by florida63** [comment]
@acv : Ok, you merge when you want because it is functional

**Pull request merged**
