### PR TITLE
start to use Semantic Versioning, will release 1.2.0 tag after this merge

### LINKED ISSUE #59: use branch and tag, don't change on master
git use branch for write code, use tag for release a version, should not directly change the master.
docs is here:
http://rogerdudler.github.io/git-guide/index.html

suggestion: use branch and tag

### PR DESCRIPTION
**Pull request by sinkcup**
because "domain whitelist" is a new feature, so we need change the "MINOR_VERSION", should be 1.2.0 .
after many discussions, we are agreeing.
tag is important for us, should not be delayed. we can fork openwrt/packages and commit package for it until we have tags. And milestone will be created after tag.
I will release 1.2.0 tag after this merge, and we can close #59

### CODE REVIEW

**Comment by florida63** [comment]
update this line:

WIFIDOG_VERSION=$WIFIDOG_MAJOR_VERSION.$WIFIDOG_MINOR_VERSION.$WIFIDOG_MICRO_VERSION

**Comment by champtar** [comment]
maybe you can just start at version 2.x.x or 3.x.x, so you don't need to keep the 20130917 string that will make people think wifidog hasn't been updated for ages

**Comment by mhaas** [comment]
FYI, opkg has a *--compare-versions* switch (or similar) which you can use for testing.

**Comment by sinkcup** [comment]
because of 6a65ff51ec940ffec6ec12379b9bef0c33a6cbeb , "domain white list" can't use now...
this pull request will be droped.

**Comment by mhaas** [comment]
I don't understand. Isn't domain whitelisting already merged? Did my commit break it? Or are you referring to #77?

**Comment by acv** [comment]
Am ambivalent about putting #91 before or after.

**Comment by mhaas** [comment]
@avc It's a perfect opportunity to release 1.2.1 if you break something.

**Comment by acv** [comment]
lol... I bet user avc is tired to get my notifications ;-)

**Comment by sinkcup** [comment]
@mhaas
 domain whitelist is #76, we can add domain in conf from that version, like apple.com.
and #77 is a small bug of domain whitelist, I want to fix it today, than I find it can't run ... :(

**Comment by sinkcup** [comment]
@champtar
I don't like 20130917 too ...but we need keep it, because "opkg update" need it.
see discussions at #59

**Comment by mhaas** [comment]
Or.. we just assume that nobody needs a clean update path? :)

**Comment by sinkcup** [comment]
@mhaas 

    opkg compare-versions "20090925-1" "<" "1.2.0-1" && echo "Yes"

"opkg compare-versions" tell me it can upgrade from "20090925-1" to "1.2.0-1", but it actually can't. 
look:
opkg compare-versions

**Comment by sinkcup** [comment]
@mhaas 
maybe "opkg compare-versions" is wrong, we can't use it. look:

    opkg compare-versions "1" ">=" "2" && echo "Yes"
    Yes
    opkg compare-versions "1.0.0" ">=" "2.0.0" && echo "Yes"
    Yes

**Comment by sinkcup** [comment]
I find a new method to compare version.

    vi /usr/lib/opkg/status

change it to "20130917-1"

    vi /var/opkg-lists/barrier_breaker

change it to "20130917-1.2.0".

result: we can update from "20130917-1" to "20130917-1.2.0", and can't update from "20130917-1" to "1.2.0-1", so we need keep "20130917".

**Comment by mhaas** [comment]
We could just update 20130917 to the current date, 20150317-1.2.0. This way it's less historal baggage and more an useful indicator of the release date.

**Comment by sinkcup** [comment]
@mhaas 
It's a good idea. we should use that version number in openwrt package.
who have the permission to fork github.com/openwrt/packages to this wifidog team?

**Comment by mhaas** [comment]
Probably @acv and @nbd

**Comment by champtar** [comment]
Hi all,

everybody can fork openwrt packages repo and make a PR
in the end we (on the openwrt packages repo) want one maintainer

for the package version, wifidog will not be backported to BB i think, and it's not build for CC, so there will be no update problem (please drop the date and use semver, or use the date and not semver, but not both)

quick note
```
opkg compare-versions '2.0.0' '<' '3.0.0' && echo no || echo yes
yes
```

Regards

**Comment by mhaas** [comment]
Hi @champtar,

Thanks for chiming in. We'd rather fork the packages repo into our project (must be done by an admin) so all members can contribute. We might still have one person as a maintainer contact.


We are concerned about upgrade paths if we want to provide our own packages for BB. But we also might be overcomplicating things. Would you even accept a Makefile which contains conditionals based on RELEASE?

**Comment by sinkcup** [comment]
@champtar 
we will support these 3 versions:
trunk (main development tree Chaos Calmer) : create a new package, @mhaas mayby we can use 1.2.0 ? 
see https://github.com/openwrt/packages/tree/master 

14.07 branch (Barrier Breaker) : create a new package, we can use 1.2.0
https://github.com/openwrt/packages/tree/for-14.07

12.09 branch (Attitude Adjustment) : update the existing code, version is 20090925-1, we should use 20150318-1.2.0
see https://dev.openwrt.org/browser/branches/packages_12.09/net/wifidog

**Comment by mhaas** [comment]
@sinkcup wifidog is in BB, in oldpackages. So we need that upgrade path as well.

**Comment by sinkcup** [comment]
@mhaas where is the oldpackage URI ?
I can't find it, only find two for 14.07:
https://dev.openwrt.org/browser/branches/packages_14.07
https://github.com/openwrt/packages/tree/for-14.07

I find oldpackages at here: http://wiki.openwrt.org/doc/devel/feeds
but it had been disabled.

**Comment by mhaas** [comment]
@sinkcup Yes, it's a bit confusing.

The repository on git.openwrt.org is oldpackages: http://git.openwrt.org/?p=packages.git;a=tree
In that repo, the for-14.07 branch (apparently) contains the versions as shipped with BB.

The repository on github.com is the current packages repo.

**Comment by sinkcup** [comment]
@mhaas Yes, I see it. maybe this:
trunk (main development tree Chaos Calmer) : create a new package, we can use 1.2.0
see https://github.com/openwrt/packages/tree/master

14.07 branch (Barrier Breaker) : update existing package 20130917, we should use yymmdd-1.2.0

12.09 branch (Attitude Adjustment) : update existing package 20090925, we should use yymmdd-1.2.0

**Pull request merged**
