### PR TITLE
Improve the wdctl_thread code

### PR DESCRIPTION
**Pull request by acv**
Reduce reliance on global mutex for client_list and possibly other improvements.

### CODE REVIEW

**Comment by acv** [comment]
Good point. Hmmm, maybe not worth it.

**Comment by mhaas** [comment]
Well, that's what you get for restarting wifidog :>

**Comment by acv** [comment]
I'll add a commit that will dump the client_list from the original list under mutex lock. I stand by the separation of the unix socket creation code however, that was exactly the same long stretch of code in two places.

**Comment by mhaas** [comment]
On 04/02/2015 02:31 PM, Alexandre Carmel-Veilleux wrote:
> I'll add a commit that will dump the client_list from the original list
> under mutex lock. I stand by the separation of the unix socket creation
> code however, that was exactly the same long stretch of code in two places.
> 

Yup, that's very good!

**Pull request merged**
