### PR TITLE
Vars fixes on openWRT-portable-Makefile

### PR DESCRIPTION
**Pull request by databeille**
... and replace optional "ExternalInterface" by mandatory "GatewayInterface"

### CODE REVIEW

**Comment by mhaas** [comment]
Can we reload on any wifidog.conf change? I have to admit that procd is not that well-documented.

**Comment by databeille** [comment]
It seems we can include references to wifidog.conf in start() and service_triggers().
It is in start() :  procd_set_param file \$$WIFIDOG_CONF
It could/should be in service_triggers() : procd_add_reload_trigger \$$WIFIDOG_CONF

procd seems to be in testing phase, doc is uncomplete, code is confusing ( 	procd_add_reload_interface_trigger makes a call to procd_add_interface_trigger, whereas procd_add_reload_trigger makes a call to procd_add_config_trigger).

I think we should focus on fixing the use of wifidog-init before moving to this step.

references:
https://dev.openwrt.org/browser/trunk/package/system/procd/files/procd.sh
http://wiki.openwrt.org/inbox/procd-init-scripts

**Comment by acv** [comment]
@sinkcup has reverted your patch commit so can you remake this PR with the original files?

**Comment by sinkcup** [comment]
I used "procd_add_reload_trigger" five months ago, it do nothing.

**Comment by databeille** [comment]
I agree, and it is hard to figure out because of the poor documentation.
If we have a look to others packages, procd_add_reload_trigger seems used to handle uci datas.

In general, with procd, references to /etc/wifidog.conf should probably be replaced by a uci compliant config file. And I don't know much about that.

**Comment by sinkcup** [comment]
UCI is better for management(shell and luci web).
new packages are using it.
We can transfer to UCI too.

**Comment by mhaas** [comment]
@sinkcup Excellent idea. And then the next step: create a luci module.

I guess we can have separate issues for the Makefile and for UCI. UCI likely is a bit of work.

**Pull request closed without merging**
