### PR TITLE
Add ipset support in Firewall

### LINKED ISSUE #60: Allow ipsets for auth server / in firewall rules
Hello,

my [auth server](https://github.com/mhaas/fbwlan/) uses Facebook to log in users. FB uses several IPs as part of their CDN which change all the time. I handle this by using the ipset function in dnsmasq. Dnsmasq adds all IPs for facebook.com (etc) to an ipset which I then allow with this rule:

    iptables -A WiFiDog_br-lan_AuthServers -m set --match-set fb dst -j ACCEPT

The problem is that Wifidog flushes iptables on start, so I have to *sleep* for 10s or so before applying the rule. That's ugly and error-prone. So I'd like to humbly request that FirewallRule be extended with ipset support. Refs issue #38.

### PR DESCRIPTION
**Pull request by mhaas**
Adds to-ipset to Firewall rule.
This is useful if you want to block or allow externally specified ips at runtime. Fixes #60

### CODE REVIEW

**Comment by florida63** [comment]
Good news.

I have not looked in detail or even tested your work, but it does not fail thee update wifidog.conf?

Best regards

**Comment by mhaas** [comment]
I have added an example in wifidog.conf in 19891a9. If that's what you were asking.

Am 10. März 2015 21:48:59 MEZ, schrieb florida63 <notifications@github.com>:

**Comment by florida63** [comment]
Ok, sorry I had not seen, that was exactly my question.

Personally, I see no downside to pushing your code. However, it requires having other user feedback.

**Comment by acv** [comment]
I created an issue (#68) that can be used to cherry pick 2e6475cf99b54f12b1fc5ad041cb1003f83d00c4 to and possibly extend it for -Wall warnings?

**Comment by acv** [comment]
I cherry picked 2e6475c, 78d4f58 and 3134004 into pull request #69

**Comment by mhaas** [comment]
I just updated the branch. The feature works fine for me. Anyone want to merge?

**Comment by florida63** [comment]
It works well here.

**Comment by mhaas** [comment]
I'll merge tomorrow unless someone objects.

**Comment by acv** [comment]
Let's cut the chase.

**Pull request merged**
