### PR TITLE
Implementation of 511 Network Authentication

### PR DESCRIPTION
**Pull request by lgaitan**
Hi,

RFC #6585, defines a new response reader, code 511 Network Authentication Required, its purpose is "mitigate problems caused by captive portals".

All requests answered with 511 will not be cached and is this is the only way for the client machine to identify an hotspot and auto redirect to login page. Windows and Apple OSX automatically detect it.

One of my main issues running wifidog is make the user redirected to login, this fix it.

Thank you.

### CODE REVIEW

**Comment by Tr4cer0ute** [comment]
Hi @LGaitan. Thanks for this. I will give it a try during the week and I revert.

**Comment by Tr4cer0ute** [comment]
@LGaitan will this result in HTTPS login page redirection ? At this point users are only redirected to login page if they put an HTTP link. It it's true this will be a new Milestone for WD gateway.

**Comment by mhaas** [comment]
@tr4cer0ute No.

@lgaitan how is support on Android for status code 511? I could only find a single reference for that RFC related to Android, but I did not look very deeply.

**Comment by LGaitan** [comment]
@mhaas Android has it's own service for detecting hotspots since android 4.2, and apple ios also have their own but im not sure since when.

For what i've found chromium have a mechanism that send requests to www.gstatic.com/generate_204 and expect an 204 No Content response.
[Google Docs](https://docs.google.com/document/d/1k-gP2sswzYNvryu9NcgN7q5XrsMlUdlUdoW9WRaEmfM/edit)

All newer systems have their own detection mechanism, if the user has an outdated device it's browser will be able to detect and handle it.

**Comment by LGaitan** [comment]
@Tr4cer0ute As a wrote above, there are some mechanisms to handle hotspots with tls connections. Check [Google Docs](https://docs.google.com/document/d/1k-gP2sswzYNvryu9NcgN7q5XrsMlUdlUdoW9WRaEmfM/edit)

If you want to intercept https connections, you should create a new instance of webserver listening to 443, have a valid ssl certificate and emit a 511 Network Authentication Required when receiving requests.

**Pull request closed without merging**
