### PR TITLE
FirewallRule allow domain, and auto pass subdomain

### PR DESCRIPTION
**Pull request by sinkcup**
see #65

### CODE REVIEW

**Comment by sinkcup** [comment]
"This organization has no public members. "
Please check this code, I am skilled on c/shell language, coding standard and git flow, I can make wifidog better.
I want  to join wifidog organization on github, could I?

**Comment by benoitg** [comment]
Sure, sent an invite

**Comment by databeille** [comment]
It would be nice if dynamic IPs could be updated (for example clients.l.google.com).

**Comment by acv** [comment]
Isn't there another feature that @mhaas added that does the equivalent of keeping track of dynamic IPs?

**Comment by databeille** [comment]
Ok, it seems it's handled by this commit: https://github.com/wifidog/wifidog-gateway/commit/6a65ff51ec940ffec6ec12379b9bef0c33a6cbeb

My iptable lacks a module:
<pre>[7][Fri May 15 10:37:17 2015][4701](fw_iptables.c:108) Executing command: iptables -t nat -A WiFiDog_br-ext_Global -m set --match-set clients.l.google.com dst -j ACCEPT
[7][Fri May 15 10:37:17 2015][4701](util.c:113) Waiting for PID 4884 to exit
iptables v1.4.21: Kernel module xt_set is not loaded in.</pre>

**Pull request merged**
